export enum ESort {
    DATE_ASC = "DATE_ASC",
    DATE_DESC = "DATE_DESC",
    DATE_CREATION_DESC = "DATE_CREATION_DESC",
    DATE_CREATION_ASC = "DATE_CREATION_ASC",
    CLICKED_DESC = "CLICKED_DESC",
    CLICKED_ASC = "CLICKED_ASC"
}