version: '3'
services:
  gtb_container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ../:/app_gtb:rw
      - /app_gtb/front/node_modules

      - ~/.ssh:/.ssh
    ports:
      - "5000:5000"
      - '3000:3000'
    networks:
      - backend_serv
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: gtb
      MONGO_INITDB_ROOT_PASSWORD: gtb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: gtb
      ME_CONFIG_MONGODB_ADMINPASSWORD: gtb

networks:
  backend_serv:
    driver: "bridge"
