version: '3'
services:
  gtb_container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ../:/app_gtb:rw
      - /app_gtb/front/node_modules

      - ~/.ssh:/.ssh
    ports:
      - "5000:5000"
      - '3000:3000'
    networks:
      - backend_serv
    depends_on:
      - db
  # db:
  #   image: "mcr.microsoft.com/mssql/server:2017-CU11-ubuntu"
  #   environment:
  #     SA_PASSWORD: "Your_password123"
  #     ACCEPT_EULA: "Y"
  #   volumes:
  #     - ../data:/var/opt/mssql:rw
  #   ports:
  #     - "1433:1433"
  #   networks:
  #     - backend_serv


networks:
  backend_serv:
    driver: "bridge"
